name: Disallow "On Hold" PRs
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label-check:
    if: github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: danielchabr/pr-labels-checker@e1d7e79aa0933af1728011705a30528a279874fd
        with:
          id: check-labels
          hasNone: On Hold
          githubToken: ${{ secrets.GITHUB_TOKEN }}
